language: lisp
sudo: required

env:
  matrix:
    - LISP=abcl
    - LISP=allegro
    - LISP=sbcl
    - LISP=sbcl32
    - LISP=ccl
    - LISP=ccl32
    - LISP=clisp
    - LISP=clisp32
    - LISP=cmucl
    - LISP=ecl

matrix:
  allow_failures:
    # CIM not available for CMUCL
    - env: LISP=cmucl
    # issue #16
    - env: LISP=allegro

# either use a local install.sh script or install it via curl. Feel
# free to simplify this section in your own .travis.yml file.
install:
  - if [ -x ./install.sh ] && head -2 ./install.sh | grep '^# cl-travis' > /dev/null;
    then
      ./install.sh;
    else
      curl https://raw.githubusercontent.com/luismbo/cl-travis/master/install.sh | sh;
    fi     
  - 'cd $HOME/quicklisp/local-projects && git clone https://git.elangley.org/git/edwlan/fwoar.lisputils'

# this serves as an example of how to use the 'cl' script (provided by
# CIM) to test your Lisp project. Here, we're using the RT framework
# to do unit testing; other frameworks will have different ways of
# determining whether a test suite fails or succeeds.
script:
  - cl -e '(ql:quickload :stream-provider)'
  - cl -e '(ql:quickload :stream-provider)
           (asdf:test-op :stream-provider)';
    [ $? -eq 1 ]
